FORMAT: 1A
HOST: https://assets-int.bqws.io/

# Assets
This module controls the user assets. When a user purchases a product, that product could have a number of assets asociated with it. If the user want to access to the resources witch thouse assets give access, he needs to use this module.

# Group Upgrade Token

## Access to user assets [/v1.0/asset/access]
### Access [GET]

###Header###
|Name|Description|Type|Required|Default|
|------|-----|-----------|:--:|:--|
|No-Redirect|If true, returns 204 with the header "Location" and the client should perform the redirection manualy. Else the request returns 303 to redirect to IAM.|Boolean||false|


+ Response 303

    + Header
    
            Location: https://iam-int.bqws.io/v1.0/token/upgrade?assertion=asdhaewodnwodanwasdasdwefr230r20r


## Assets [/v1.0/asset]
this endpoint allow to read and create assets. 

### Get assets [GET]

###Fields###
|Name|Description|Type|Required|
|----|-----------|----|:------:|
|id  |asset identifier|String|
|userId|User identifier|String|
|name|Define the asset|String|
|productId|Product that contains this asset|String|
|expire|Timestamp|Date|
|active|asset is validated|Boolean|
|scopes|String array with scopes associated with the asset|String|



###Errors###
|Status|Error|Description|
|------|-----|-----------|
|401  |unauthorized|If the access_token is not associated with any user.|
|404  |not_found|When asset not exist.|

+ Request
    + Header
    
            Authorization: Bearer {access_token}

+ Response 200 (application/json)


        { 
        "_id" : "53aaadfbe4b005e52b14ff37", 
        "userId" : "fooid", 
        "name" : "assettest", 
        "productId": "12345",
        "expire" : ISODate("2025-01-01T00:01:00Z"), 
        "active" : true, 
        "scopes" : [
                "assets:test"
                ] 
        }

# Group Assets management
Avaliable from version 0.21.0
## Assets [/v1.0/asset/all]
this endpoint allow to read all assets. 

### Get assets [GET]

###Fields###
|Name|Description|Type|Required|
|----|-----------|----|:------:|
|id  |asset identifier|String|
|userId|User identifier|String|
|name|Define the asset|String|
|productId|Product that contains this asset|String|
|expire|Timestamp|Date|
|active|asset is validated|Boolean|
|scopes|String array with scopes associated with the asset|String|



###Errors###
|Status|Error|Description|
|------|-----|-----------|
|401  |unauthorized|If the access_token is not associated with any user.|
|404  |not_found|When asset not exist.|

+ Request
    + Header
    
            Authorization: Bearer {access_token}

+ Response 200 (application/json)

        [
            { 
            "_id" : "53aaadfbe4b005e52b14ff37", 
            "userId" : "fooid", 
            "name" : "assettest", 
            "productId": "12345",
            "expire" : ISODate("2025-01-01T00:01:00Z"), 
            "active" : true, 
            "scopes" : [
                    "assets:test"
                    ] 
            }
        ]


## Assets [/v1.0/asset]
this endpoint allow to create assets. 

### Create assets [POST]

###Fields###
|Name|Description|Type|Required|
|----|-----------|----|:------:|
|id  |asset identifier|String|
|userId|User identifier|String|
|name|Define the asset|String|
|productId|Product that contains this asset|String|
|expire|Timestamp|Date|
|active|asset is validated|Boolean|
|scopes|String array with scopes associated with the asset|String|



###Errors###
|Status|Error|Description|
|------|-----|-----------|
|401  |unauthorized|If the access_token is not associated with any user.|
|422  |invalid_entity|JSON doesn't correspond to assets or is empty|

+ Request (application/json)
    + Header
    
            Authorization: Bearer {access_token}

    + Body
    
            { 
                "userId" : "fooid", 
                "name" : "assettest", 
                "productId": "12345",
                "expire" : ISODate("2025-01-01T00:01:00Z"), 
                "active" : true, 
                "scopes" : [
                    "assets:test"
                ] 
            }

+ Response 201 
    + Header
    
            Location: http://assets.int.bqreaders.com/v1.0/assets/asset/{newId}

## Assets [/v1.0/asset/{id}]
this endpoint allow to read and delete assets. 

### Get assets [GET]

###Fields###
|Name|Description|Type|Required|
|----|-----------|----|:------:|
|id  |asset identifier|String|
|userId|User identifier|String|
|name|Define the asset|String|
|productId|Product that contains this asset|String|
|expire|Timestamp|Date|
|active|asset is validated|Boolean|
|scopes|String array with scopes associated with the asset|String|



###Errors###
|Status|Error|Description|
|------|-----|-----------|
|401  |unauthorized|If the access_token is not associated with any user.|
|404  |not_found|When asset not exist.|

+ Request
    + Header
    
            Authorization: Bearer {access_token}

+ Response 200 (application/json)

        [
            { 
                "_id" : "53aaadfbe4b005e52b14ff37", 
                "userId" : "fooid", 
                "name" : "assettest", 
                "productId": "12345",
                "expire" : ISODate("2025-01-01T00:01:00Z"), 
                "active" : true, 
                "scopes" : [
                        "assets:test"
                        ] 
            }
        ]



### Delete assets [DELETE]


###Errors###
|Status|Error|Description|
|------|-----|-----------|
|401  |unauthorized|If the access_token is not associated with any user.|
|404  |not_found|When asset not exist.|

+ Request (application/json)
    + Header
    
            Authorization: Bearer {access_token}


+ Response 204

