FORMAT: 1A
HOST: https://assets-int.bqws.io/

# Assets
This module controls the user assets. When a user purchases a product, that product could have a number of assets asociated with it. If the user want to access to the resources witch thouse assets give access, he needs to use this module.

# Group Asset
Operations with assets

## Access to user assets [/v1.0/asset/access]
### Access [GET]

###Query Parameter Fields###
|Name|Description|Type|Required|Default|
|------|-----|-----------|:--:|:--|
|redirect|If true, the request returns 303 to redirect to IAM. Else, returns 200 with the header "Location" and the client should perform the redirection manualy.|Boolean||true|

+ Response 303

    + Header
    
            Location: https://iam-int.bqws.io/v1.0/token/upgrade?assertion=asdhaewodnwodanwasdasdwefr230r20r



## Get User Assets [/v1.0/assets/asset]
this endpoint allow to read the user assets. 

### Get assets [GET]

###Fields###
|Name|Description|Type|Required|
|----|-----------|----|:------:|
|id  |asset identifier|String|
|userId|User identifier|String|
|name|Define the asset|String|
|expire|Date when asset ends in ISO8601 period format (e.g. P1y2m3d)|Date|
|active|asset is validated|Boolean|
|scopes|String array with scopes associated with the asset|String|



###Errors###
|Status|Error|Description|
|------|-----|-----------|
|401  |unauthorized|If the access_token is not associated with any user.|
|404  |not_found|When asset not exist.|

+ Request
    + Header
    
            Authorization: Bearer {access_token}

+ Response 200 (application/json)


        { 
        "_id" : "53aaadfbe4b005e52b14ff37", 
        "userId" : "fooid", 
        "name" : "assettest", 
        "expire" : ISODate("2025-01-01T00:01:00Z"), 
        "active" : true, 
        "scopes" : [
                "assets:test"
                ] 
        }

